import com.study.config.Config;
import com.study.dao.UserDao;
import com.study.entity.Person;
import com.study.entity.User;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

/**
 * @author zhutongtong
 * @date 2022/6/22 16:24
 */
public class MyApplication {
//	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
//	private UserRepository userRepository;

	public static void main(String[] args) {

		AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(Config.class);
		Person person = context.getBean("person", Person.class);


		UserDao userDao = context.getBean(UserDao.class);
		User byId = userDao.getById(1);
		System.out.println();

	}


}
