[[testing-resources]]
= Further Resources
See the following resources for more information about testing:

* https://www.junit.org/[JUnit]: "A programmer-friendly testing framework for Java and the JVM".
  Used by the Spring Framework in its test suite and supported in the
  xref:testing/testcontext-framework.adoc[Spring TestContext Framework].
* https://testng.org/[TestNG]: A testing framework inspired by JUnit with added support
  for test groups, data-driven testing, distributed testing, and other features. Supported
  in the xref:testing/testcontext-framework.adoc[Spring TestContext Framework]
* {assertj-docs}[AssertJ]: "Fluent assertions for Java",
  including support for Java 8 lambdas, streams, and numerous other features.
* https://en.wikipedia.org/wiki/Mock_Object[Mock Objects]: Article in Wikipedia.
* http://www.mockobjects.com/[MockObjects.com]: Web site dedicated to mock objects, a
  technique for improving the design of code within test-driven development.
* https://mockito.github.io[Mockito]: Java mock library based on the
  http://xunitpatterns.com/Test%20Spy.html[Test Spy] pattern. Used by the Spring Framework
  in its test suite.
* https://easymock.org/[EasyMock]: Java library "that provides Mock Objects for
  interfaces (and objects through the class extension) by generating them on the fly using
  Java's proxy mechanism."
* https://jmock.org/[JMock]: Library that supports test-driven development of Java code
  with mock objects.
* https://www.dbunit.org/[DbUnit]: JUnit extension (also usable with Ant and Maven) that
  is targeted at database-driven projects and, among other things, puts your database into
  a known state between test runs.
* {testcontainers-site}[Testcontainers]: Java library that supports JUnit
  tests, providing lightweight, throwaway instances of common databases, Selenium web
  browsers, or anything else that can run in a Docker container.
* https://sourceforge.net/projects/grinder/[The Grinder]: Java load testing framework.
* https://github.com/Ninja-Squad/springmockk[SpringMockK]: Support for Spring Boot
  integration tests written in Kotlin using https://mockk.io/[MockK] instead of Mockito.
