// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package org.springframework.protobuf;

public interface SecondMsgOrBuilder
    extends com.google.protobuf.MessageOrBuilder {

  // optional int32 blah = 1;
  /**
   * <code>optional int32 blah = 1;</code>
   */
  boolean hasBlah();
  /**
   * <code>optional int32 blah = 1;</code>
   */
  int getBlah();
}
