//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.08 at 12:41:36 PM CET 
//

package org.springframework.oxm.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flight" type="{http://samples.springframework.org/flight}flightType"
 * maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"flight"})
@XmlRootElement(name = "flights")
public class Flights {

	@XmlElement(required = true)
	protected List<FlightType> flight;

	/**
	 * Gets the value of the flight property.
	 *
	 * <p> This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make
	 * to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the flight property.
	 *
	 * <p> For example, to add a new item, do as follows:
	 * <pre>
	 *    getFlight().add(newItem);
	 * </pre>
	 *
	 *
	 * <p> Objects of the following type(s) are allowed in the list {@link FlightType }
	 */
	public List<FlightType> getFlight() {
		if (flight == null) {
			flight = new ArrayList<FlightType>();
		}
		return this.flight;
	}

}
