ruby docbookrx.rb ./dynamic-languages.xml > ./dynamic-languages.adoc
ruby docbookrx.rb ./testing.xml > ./testing.adoc
ruby docbookrx.rb ./spring.tld.xml > ./spring.tld.adoc
ruby docbookrx.rb ./transaction.xml > ./transaction.adoc
ruby docbookrx.rb ./beans.xml > ./beans.adoc
ruby docbookrx.rb ./resources.xml > ./resources.adoc
ruby docbookrx.rb ./index.xml > ./index.adoc
ruby docbookrx.rb ./beans-dependencies.xml > ./beans-dependencies.adoc
ruby docbookrx.rb ./xml-custom.xml > ./xml-custom.adoc
ruby docbookrx.rb ./beans-java.xml > ./beans-java.adoc
ruby docbookrx.rb ./mail.xml > ./mail.adoc
ruby docbookrx.rb ./beans-extension-points.xml > ./beans-extension-points.adoc
ruby docbookrx.rb ./beans-annotation-config.xml > ./beans-annotation-config.adoc
ruby docbookrx.rb ./migration-3.1.xml > ./migration-3.1.adoc
ruby docbookrx.rb ./spring-form.tld.xml > ./spring-form.tld.adoc
ruby docbookrx.rb ./aop-api.xml > ./aop-api.adoc
ruby docbookrx.rb ./cci.xml > ./cci.adoc
ruby docbookrx.rb ./beans-context-additional.xml > ./beans-context-additional.adoc
ruby docbookrx.rb ./new-in-3.1.xml > ./new-in-3.1.adoc
ruby docbookrx.rb ./remoting.xml > ./remoting.adoc
ruby docbookrx.rb ./jmx.xml > ./jmx.adoc
ruby docbookrx.rb ./portlet.xml > ./portlet.adoc
ruby docbookrx.rb ./classic-spring.xml > ./classic-spring.adoc
ruby docbookrx.rb ./new-in-3.0.xml > ./new-in-3.0.adoc
ruby docbookrx.rb ./aop.xml > ./aop.adoc
ruby docbookrx.rb ./new-in-3.2.xml > ./new-in-3.2.adoc
ruby docbookrx.rb ./beans-standard-annotations.xml > ./beans-standard-annotations.adoc
ruby docbookrx.rb ./oxm.xml > ./oxm.adoc
ruby docbookrx.rb ./jms.xml > ./jms.adoc
ruby docbookrx.rb ./classic-aop-spring.xml > ./classic-aop-spring.adoc
ruby docbookrx.rb ./xsd-configuration.xml > ./xsd-configuration.adoc
ruby docbookrx.rb ./ejb.xml > ./ejb.adoc
ruby docbookrx.rb ./beans-classpath-scanning.xml > ./beans-classpath-scanning.adoc
ruby docbookrx.rb ./view.xml > ./view.adoc
ruby docbookrx.rb ./orm.xml > ./orm.adoc
ruby docbookrx.rb ./migration-3.2.xml > ./migration-3.2.adoc
ruby docbookrx.rb ./beans-customizing.xml > ./beans-customizing.adoc
ruby docbookrx.rb ./mvc.xml > ./mvc.adoc
ruby docbookrx.rb ./web-integration.xml > ./web-integration.adoc
ruby docbookrx.rb ./jdbc.xml > ./jdbc.adoc
ruby docbookrx.rb ./overview.xml > ./overview.adoc
ruby docbookrx.rb ./swf-sidebar.xml > ./swf-sidebar.adoc
ruby docbookrx.rb ./validation.xml > ./validation.adoc
ruby docbookrx.rb ./dao.xml > ./dao.adoc
ruby docbookrx.rb ./expressions.xml > ./expressions.adoc
ruby docbookrx.rb ./scheduling.xml > ./scheduling.adoc
ruby docbookrx.rb ./beans-scopes.xml > ./beans-scopes.adoc
ruby docbookrx.rb ./cache.xml > ./cache.adoc
ruby docbookrx.rb ./preface.xml > ./preface.adoc
