
= Task Execution and Scheduling

== Introduction

The Spring Framework provides abstractions for asynchronous execution and scheduling of tasks with the [interface]`TaskExecutor` and [interface]`TaskScheduler` interfaces, respectively.
Spring also features implementations of those interfaces that support thread pools or delegation to CommonJ within an application server environment.
Ultimately the use of these implementations behind the common interfaces abstracts away the differences between Java SE 5, Java SE 6 and Java EE environments.

Spring also features integration classes for supporting scheduling with the [class]`Timer`, part of the JDK since 1.3, and the Quartz Scheduler (<<,>>).
Both of those schedulers are set up using a [interface]`FactoryBean` with optional references to [class]`Timer` or [class]`Trigger` instances, respectively.
Furthermore, a convenience class for both the Quartz Scheduler and the [class]`Timer` is available that allows you to invoke a method of an existing target object (analogous to the normal [class]`MethodInvokingFactoryBean` operation).

== The Spring [interface]`TaskExecutor` abstraction

Spring 2.0 introduces a new abstraction for dealing with executors.
Executors are the Java 5 name for the concept of thread pools.
The "executor" naming is due to the fact that there is no guarantee that the underlying implementation is actually a pool; an executor may be single-threaded or even synchronous.
Spring's abstraction hides implementation details between Java SE 1.4, Java SE 5 and Java EE environments.

Spring's [interface]`TaskExecutor` interface is identical to the [class]`java.util.concurrent.Executor` interface.
In fact, its primary reason for existence is to abstract away the need for Java 5 when using thread pools.
The interface has a single method [class]`execute(Runnable task)` that accepts a task for execution based on the semantics and configuration of the thread pool.

The [interface]`TaskExecutor` was originally created to give other Spring components an abstraction for thread pooling where needed.
Components such as the [class]`ApplicationEventMulticaster`, JMS's [class]`AbstractMessageListenerContainer`, and Quartz integration all use the [interface]`TaskExecutor` abstraction to pool threads.
However, if your beans need thread pooling behavior, it is possible to use this abstraction for your own needs.

=== [interface]`TaskExecutor` types

There are a number of pre-built implementations of [interface]`TaskExecutor` included with the Spring distribution.
In all likelihood, you shouldn't ever need to implement your own.

* [class]`SimpleAsyncTaskExecutor`
+
This implementation does not reuse any threads, rather it starts up a new thread for each invocation.
However, it does support a concurrency limit which will block any invocations that are over the limit until a slot has been freed up.
If you're looking for true pooling, keep scrolling further down the page.

* [class]`SyncTaskExecutor`
+
This implementation doesn't execute invocations asynchronously.
Instead, each invocation takes place in the calling thread.
It is primarily used in situations where multithreading isn't necessary such as simple test cases.

* [class]`ConcurrentTaskExecutor`
+
This implementation is a wrapper for a Java 5 [class]`java.util.concurrent.Executor`.
There is an alternative, [class]`ThreadPoolTaskExecutor`, that exposes the [class]`Executor` configuration parameters as bean properties.
It is rare to need to use the [class]`ConcurrentTaskExecutor` but if the <<threadPoolTaskExecutor,[class]`ThreadPoolTaskExecutor`>> isn't robust enough for your needs, the [class]`ConcurrentTaskExecutor` is an alternative.

* [class]`SimpleThreadPoolTaskExecutor`
+
This implementation is actually a subclass of Quartz's [class]`SimpleThreadPool` which listens to Spring's lifecycle callbacks.
This is typically used when you have a thread pool that may need to be shared by both Quartz and non-Quartz components.

* [class]`ThreadPoolTaskExecutor`
+
[sidebar]
It is not possible to use any backport or alternate versions of the [class]`java.util.concurrent` package with this implementation.
Both Doug Lea's and Dawid Kurzyniec's implementations use different package structures which will prevent them from working correctly.
+
This implementation can only be used in a Java 5 environment but is also the most commonly used one in that environment.
It exposes bean properties for configuring a [class]`java.util.concurrent.ThreadPoolExecutor` and wraps it in a [interface]`TaskExecutor`.
If you need something advanced such as a [class]`ScheduledThreadPoolExecutor`, it is recommended that you use a <<concurrentTaskExecutor,[class]`ConcurrentTaskExecutor`>> instead.

* [class]`TimerTaskExecutor`
+
This implementation uses a single [class]`TimerTask` as its backing implementation.
It's different from the <<syncTaskExecutor,[class]`SyncTaskExecutor`>> in that the method invocations are executed in a separate thread, although they are synchronous in that thread.

* [class]`WorkManagerTaskExecutor`
+
[sidebar]
CommonJ is a set of specifications jointly developed between BEA and IBM. These specifications are not Java EE standards, but are standard across BEA's and IBM's Application Server implementations.
+
This implementation uses the CommonJ WorkManager as its backing implementation and is the central convenience class for setting up a CommonJ WorkManager reference in a Spring context.
Similar to the <<simpleThreadPoolTaskExecutor,[class]`SimpleThreadPoolTaskExecutor`>>, this class implements the WorkManager interface and therefore can be used directly as a WorkManager as well.


=== Using a [interface]`TaskExecutor`

Spring's [interface]`TaskExecutor` implementations are used as simple JavaBeans.
In the example below, we define a bean that uses the [class]`ThreadPoolTaskExecutor` to asynchronously print out a set of messages.

[source,java]
----
import org.springframework.core.task.TaskExecutor;

public class TaskExecutorExample {

  private class MessagePrinterTask implements Runnable {

    private String message;

    public MessagePrinterTask(String message) {
      this.message = message;
    }

    public void run() {
      System.out.println(message);
    }

  }

  private TaskExecutor taskExecutor;

  public TaskExecutorExample(TaskExecutor taskExecutor) {
    this.taskExecutor = taskExecutor;
  }

  public void printMessages() {
    for(int i = 0; i < 25; i++) {
      taskExecutor.execute(new MessagePrinterTask("Message" + i));
    }
  }
}
----

As you can see, rather than retrieving a thread from the pool and executing yourself, you add your [class]`Runnable` to the queue and the [interface]`TaskExecutor` uses its internal rules to decide when the task gets executed.

To configure the rules that the [interface]`TaskExecutor` will use, simple bean properties have been exposed.

[source,xml]
----
<bean id="taskExecutor" class="org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor">
  <property name="corePoolSize" value="5" />
  <property name="maxPoolSize" value="10" />
  <property name="queueCapacity" value="25" />
</bean>

<bean id="taskExecutorExample" class="TaskExecutorExample">
  <constructor-arg ref="taskExecutor" />
</bean>
----

== The Spring [interface]`TaskScheduler` abstraction

In addition to the [interface]`TaskExecutor` abstraction, Spring 3.0 introduces a [interface]`TaskScheduler` with a variety of methods for scheduling tasks to run at some point in the future.

[source,java]
----
public interface TaskScheduler {

    ScheduledFuture schedule(Runnable task, Trigger trigger);

    ScheduledFuture schedule(Runnable task, Date startTime);

    ScheduledFuture scheduleAtFixedRate(Runnable task, Date startTime, long period);

    ScheduledFuture scheduleAtFixedRate(Runnable task, long period);

    ScheduledFuture scheduleWithFixedDelay(Runnable task, Date startTime, long delay);

    ScheduledFuture scheduleWithFixedDelay(Runnable task, long delay);

}
----

The simplest method is the one named 'schedule' that takes a [interface]`Runnable` and [class]`Date` only.
That will cause the task to run once after the specified time.
All of the other methods are capable of scheduling tasks to run repeatedly.
The fixed-rate and fixed-delay methods are for simple, periodic execution, but the method that accepts a Trigger is much more flexible.

=== The [interface]`Trigger` interface

The [interface]`Trigger` interface is essentially inspired by JSR-236, which, as of Spring 3.0, has not yet been officially implemented.
The basic idea of the [interface]`Trigger` is that execution times may be determined based on past execution outcomes or even arbitrary conditions.
If these determinations do take into account the outcome of the preceding execution, that information is available within a [interface]`TriggerContext`.
The [interface]`Trigger` interface itself is quite simple:

[source,java]
----
public interface Trigger {

    Date nextExecutionTime(TriggerContext triggerContext);

}
----

As you can see, the [interface]`TriggerContext` is the most important part.
It encapsulates all of the relevant data, and is open for extension in the future if necessary.
The [interface]`TriggerContext` is an interface (a [class]`SimpleTriggerContext` implementation is used by default).
Here you can see what methods are available for [interface]`Trigger` implementations.

[source,java]
----
public interface TriggerContext {

    Date lastScheduledExecutionTime();

    Date lastActualExecutionTime();

    Date lastCompletionTime();

}
----

=== [interface]`Trigger` implementations

Spring provides two implementations of the [interface]`Trigger` interface.
The most interesting one is the [class]`CronTrigger`.
It enables the scheduling of tasks based on cron expressions.
For example the following task is being scheduled to run 15 minutes past each hour but only during the 9-to-5 "business hours" on weekdays.

[source,java]
----
scheduler.schedule(task, new CronTrigger("* 15 9-17 * * MON-FRI"));
----

The other out-of-the-box implementation is a [class]`PeriodicTrigger` that accepts a fixed period, an optional initial delay value, and a boolean to indicate whether the period should be interpreted as a fixed-rate or a fixed-delay.
Since the [interface]`TaskScheduler` interface already defines methods for scheduling tasks at a fixed-rate or with a fixed-delay, those methods should be used directly whenever possible.
The value of the [class]`PeriodicTrigger` implementation is that it can be used within components that rely on the [interface]`Trigger` abstraction.
For example, it may be convenient to allow periodic triggers, cron-based triggers, and even custom trigger implementations to be used interchangeably.
Such a component could take advantage of dependency injection so that such [interface]`Triggers` could be configured externally.

=== [interface]`TaskScheduler` implementations

As with Spring's [interface]`TaskExecutor` abstraction, the primary benefit of the [interface]`TaskScheduler` is that code relying on scheduling behavior need not be coupled to a particular scheduler implementation.
The flexibility this provides is particularly relevant when running within Application Server environments where threads should not be created directly by the application itself.
For such cases, Spring provides a [class]`TimerManagerTaskScheduler` that delegates to a CommonJ TimerManager instance, typically configured with a JNDI-lookup.

A simpler alternative, the [class]`ThreadPoolTaskScheduler`, can be used whenever external thread management is not a requirement.
Internally, it delegates to a [interface]`ScheduledExecutorService` instance.
[class]`ThreadPoolTaskScheduler` actually implements Spring's [interface]`TaskExecutor` interface as well, so that a single instance can be used for asynchronous execution _as soon as possible_ as well as scheduled, and potentially recurring, executions.

== Annotation Support for Scheduling and Asynchronous Execution

Spring provides annotation support for both task scheduling and asynchronous method execution.

=== Enable scheduling annotations

To enable support for [interface]`@Scheduled` and [interface]`@Async` annotations add [interface]`@EnableScheduling` and [interface]`@EnableAsync` to one of your [interface]`@Configuration` classes:

[source,java]
----
@Configuration
@EnableAsync
@EnableScheduling
public class AppConfig {
}
----

You are free to pick and choose the relevant annotations for your application.
For example, if you only need support for [interface]`@Scheduled`, simply omit [interface]`@EnableAsync`.
For more fine-grained control you can additionally implement the [interface]`SchedulingConfigurer` and/or [interface]`AsyncConfigurer` interfaces.
See the Javadoc for full details.

If you prefer XML configuration use the `<task:annotation-driven>` element.

[source,xml]
----
<task:annotation-driven executor="myExecutor" scheduler="myScheduler"/>
<task:executor id="myExecutor" pool-size="5"/>
<task:scheduler id="myScheduler" pool-size="10"/>}
----

Notice with the above XML that an executor reference is provided for handling those tasks that correspond to methods with the [interface]`@Async` annotation, and the scheduler reference is provided for managing those methods annotated with [interface]`@Scheduled`.

=== The @Scheduled Annotation

The @Scheduled annotation can be added to a method along with trigger metadata.
For example, the following method would be invoked every 5 seconds with a fixed delay, meaning that the period will be measured from the completion time of each preceding invocation.

[source,java]
----
@Scheduled(fixedDelay=5000)
public void doSomething() {
    // something that should execute periodically
}
----

If a fixed rate execution is desired, simply change the property name specified within the annotation.
The following would be executed every 5 seconds measured between the successive start times of each invocation.

[source,java]
----
@Scheduled(fixedRate=5000)
public void doSomething() {
    // something that should execute periodically
}
----

For fixed-delay and fixed-rate tasks, an initial delay may be specified indicating the number of milliseconds to wait before the first execution of the method.


[source,java]
----
@Scheduled(initialDelay=1000, fixedRate=5000)
public void doSomething() {
    // something that should execute periodically
}
----

If simple periodic scheduling is not expressive enough, then a cron expression may be provided.
For example, the following will only execute on weekdays.

[source,java]
----
@Scheduled(cron="*/5 * * * * MON-FRI")
public void doSomething() {
    // something that should execute on weekdays only
}
----

Notice that the methods to be scheduled must have void returns and must not expect any arguments.
If the method needs to interact with other objects from the Application Context, then those would typically have been provided through dependency injection.

NOTE: Make sure that you are not initializing multiple instances of the same @Scheduled annotation class at runtime, unless you do want to schedule callbacks to each such instance.
Related to this, make sure that you do not use @Configurable on bean classes which are annotated with @Scheduled and registered as regular Spring beans with the container: You would get double initialization otherwise, once through the container and once through the @Configurable aspect, with the consequence of each @Scheduled method being invoked twice.

=== The @Async Annotation

The [interface]`@Async` annotation can be provided on a method so that invocation of that method will occur asynchronously.
In other words, the caller will return immediately upon invocation and the actual execution of the method will occur in a task that has been submitted to a Spring [interface]`TaskExecutor`.
In the simplest case, the annotation may be applied to a `void`-returning method.

[source,java]
----
@Async
void doSomething() {
    // this will be executed asynchronously
}
----

Unlike the methods annotated with the [interface]`@Scheduled` annotation, these methods can expect arguments, because they will be invoked in the "normal" way by callers at runtime rather than from a scheduled task being managed by the container.
For example, the following is a legitimate application of the [interface]`@Async` annotation.

[source,java]
----
@Async
void doSomething(String s) {
    // this will be executed asynchronously
}
----

Even methods that return a value can be invoked asynchronously.
However, such methods are required to have a [interface]`Future` typed return value.
This still provides the benefit of asynchronous execution so that the caller can perform other tasks prior to calling [method]`get()` on that Future.

[source,java]
----
@Async
Future<String> returnSomething(int i) {
    // this will be executed asynchronously
}
----

[interface]`@Async` can not be used in conjunction with lifecycle callbacks such as [interface]`@PostConstruct`.
To asynchronously initialize Spring beans you currently have to use a separate initializing Spring bean that invokes the [interface]`@Async` annotated method on the target then.

[source,java]
----
public class SampleBeanImpl implements SampleBean {

  @Async
  void doSomething() { … }
}


public class SampleBeanInititalizer {

  private final SampleBean bean;

  public SampleBeanInitializer(SampleBean bean) {
    this.bean = bean;
  }

  @PostConstruct
  public void initialize() {
    bean.doSomething();
  }
}
----

=== Executor qualification with @Async

By default when specifying [interface]`@Async` on a method, the executor that will be used is the one supplied to the 'annotation-driven' element as described above.
However, the `value` attribute of the [interface]`@Async` annotation can be used when needing to indicate that an executor other than the default should be used when executing a given method.

[source,java]
----
@Async("otherExecutor")
void doSomething(String s) {
    // this will be executed asynchronously by "otherExecutor"
}
----

In this case, "otherExecutor" may be the name of any [interface]`Executor` bean in the Spring container, or may be the name of a _qualifier_ associated with any [interface]`Executor`, e.g.
as specified with the `<qualifier>` element or Spring's [interface]`@Qualifier` annotation.

== The Task Namespace

Beginning with Spring 3.0, there is an XML namespace for configuring [interface]`TaskExecutor` and [interface]`TaskScheduler` instances.
It also provides a convenient way to configure tasks to be scheduled with a trigger.

=== The 'scheduler' element

The following element will create a [class]`ThreadPoolTaskScheduler` instance with the specified thread pool size.

[source,xml]
----
<task:scheduler id="scheduler" pool-size="10"/>
----

The value provided for the 'id' attribute will be used as the prefix for thread names within the pool.
The 'scheduler' element is relatively straightforward.
If you do not provide a 'pool-size' attribute, the default thread pool will only have a single thread.
There are no other configuration options for the scheduler.

=== The 'executor' element

The following will create a [class]`ThreadPoolTaskExecutor` instance: 
[source,xml]
----
<task:executor id="executor" pool-size="10"/>
----

As with the scheduler above, the value provided for the 'id' attribute will be used as the prefix for thread names within the pool.
As far as the pool size is concerned, the 'executor' element supports more configuration options than the 'scheduler' element.
For one thing, the thread pool for a [class]`ThreadPoolTaskExecutor` is itself more configurable.
Rather than just a single size, an executor's thread pool may have different values for the _core_ and the _max_ size.
If a single value is provided then the executor will have a fixed-size thread pool (the core and max sizes are the same).
However, the 'executor' element's 'pool-size' attribute also accepts a range in the form of "min-max".

[source,xml]
----
<task:executor id="executorWithPoolSizeRange"
                 pool-size="5-25"
                 queue-capacity="100"/>
----

As you can see from that configuration, a 'queue-capacity' value has also been provided.
The configuration of the thread pool should also be considered in light of the executor's queue capacity.
For the full description of the relationship between pool size and queue capacity, consult the documentation for <<,ThreadPoolExecutor>>.
The main idea is that when a task is submitted, the executor will first try to use a free thread if the number of active threads is currently less than the core size.
If the core size has been reached, then the task will be added to the queue as long as its capacity has not yet been reached.
Only then, if the queue's capacity _has_ been reached, will the executor create a new thread beyond the core size.
If the max size has also been reached, then the executor will reject the task.

By default, the queue is _unbounded_, but this is rarely the desired configuration, because it can lead to [class]`OutOfMemoryErrors` if enough tasks are added to that queue while all pool threads are busy.
Furthermore, if the queue is unbounded, then the max size has no effect at all.
Since the executor will always try the queue before creating a new thread beyond the core size, a queue must have a finite capacity for the thread pool to grow beyond the core size (this is why a _fixed size_ pool is the only sensible case when using an unbounded queue).

In a moment, we will review the effects of the keep-alive setting which adds yet another factor to consider when providing a pool size configuration.
First, let's consider the case, as mentioned above, when a task is rejected.
By default, when a task is rejected, a thread pool executor will throw a [class]`TaskRejectedException`.
However, the rejection policy is actually configurable.
The exception is thrown when using the default rejection policy which is the [class]`AbortPolicy` implementation.
For applications where some tasks can be skipped under heavy load, either the [class]`DiscardPolicy` or [class]`DiscardOldestPolicy` may be configured instead.
Another option that works well for applications that need to throttle the submitted tasks under heavy load is the [class]`CallerRunsPolicy`.
Instead of throwing an exception or discarding tasks, that policy will simply force the thread that is calling the submit method to run the task itself.
The idea is that such a caller will be busy while running that task and not able to submit other tasks immediately.
Therefore it provides a simple way to throttle the incoming load while maintaining the limits of the thread pool and queue.
Typically this allows the executor to "catch up" on the tasks it is handling and thereby frees up some capacity on the queue, in the pool, or both.
Any of these options can be chosen from an enumeration of values available for the 'rejection-policy' attribute on the 'executor' element.

[source,xml]
----
<task:executor id="executorWithCallerRunsPolicy"
               pool-size="5-25"
               queue-capacity="100"
               rejection-policy="CALLER_RUNS"/>
----

=== The 'scheduled-tasks' element

The most powerful feature of Spring's task namespace is the support for configuring tasks to be scheduled within a Spring Application Context.
This follows an approach similar to other "method-invokers" in Spring, such as that provided by the JMS namespace for configuring Message-driven POJOs.
Basically a "ref" attribute can point to any Spring-managed object, and the "method" attribute provides the name of a method to be invoked on that object.
Here is a simple example.

[source,xml]
----
<task:scheduled-tasks scheduler="myScheduler">
    <task:scheduled ref="beanA" method="methodA" fixed-delay="5000"/>
</task:scheduled-tasks>

<task:scheduler id="myScheduler" pool-size="10"/>
----

As you can see, the scheduler is referenced by the outer element, and each individual task includes the configuration of its trigger metadata.
In the preceding example, that metadata defines a periodic trigger with a fixed delay indicating the number of milliseconds to wait after each task execution has completed.
Another option is 'fixed-rate', indicating how often the method should be executed regardless of how long any previous execution takes.
Additionally, for both fixed-delay and fixed-rate tasks an 'initial-delay' parameter may be specified indicating the number of milliseconds to wait before the first execution of the method.
For more control, a "cron" attribute may be provided instead.
Here is an example demonstrating these other options.

[source,xml]
----
<task:scheduled-tasks scheduler="myScheduler">
    <task:scheduled ref="beanA" method="methodA" fixed-delay="5000" initial-delay="1000"/>
    <task:scheduled ref="beanB" method="methodB" fixed-rate="5000"/>
    <task:scheduled ref="beanC" method="methodC" cron="*/5 * * * * MON-FRI"/>
</task:scheduled-tasks>

<task:scheduler id="myScheduler" pool-size="10"/>
----

== Using the Quartz Scheduler

Quartz uses [class]`Trigger`, [class]`Job` and [class]`JobDetail` objects to realize scheduling of all kinds of jobs.
For the basic concepts behind Quartz, have a look at <<,>>.
For convenience purposes, Spring offers a couple of classes that simplify the usage of Quartz within Spring-based applications.

=== Using the JobDetailBean

[class]`JobDetail` objects contain all information needed to run a job.
The Spring Framework provides a [class]`JobDetailBean` that makes the [class]`JobDetail` more of an actual JavaBean with sensible defaults.
Let's have a look at an example:

[source,xml]
----

<bean name="exampleJob" class="org.springframework.scheduling.quartz.JobDetailBean">
  <property name="jobClass" value="example.ExampleJob" />
  <property name="jobDataAsMap">
    <map>
      <entry key="timeout" value="5" />
    </map>
  </property>
</bean>
----

The job detail bean has all information it needs to run the job ([class]`ExampleJob`).
The timeout is specified in the job data map.
The job data map is available through the [class]`JobExecutionContext` (passed to you at execution time), but the [class]`JobDetailBean` also maps the properties from the job data map to properties of the actual job.
So in this case, if the [class]`ExampleJob` contains a property named `timeout`, the [class]`JobDetailBean` will automatically apply it:

[source,java]
----
package example;

public class ExampleJob extends QuartzJobBean {

  private int timeout;

  /**
   * Setter called after the ExampleJob is instantiated
   * with the value from the JobDetailBean (5)
   */
  public void setTimeout(int timeout) {
    this.timeout = timeout;
  }

  protected void executeInternal(JobExecutionContext ctx) throws JobExecutionException {
      // do the actual work
  }
}
----

All additional settings from the job detail bean are of course available to you as well.

_Note: Using the `name` and
      `group` properties, you can modify the name and the
      group of the job, respectively. By default, the name of the job matches
      the bean name of the job detail bean (in the example above, this is
      `exampleJob`)._

=== Using the [class]`MethodInvokingJobDetailFactoryBean`

Often you just need to invoke a method on a specific object.
Using the [class]`MethodInvokingJobDetailFactoryBean` you can do exactly this:

[source,xml]
----
<bean id="jobDetail" class="org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean">
  <property name="targetObject" ref="exampleBusinessObject" />
  <property name="targetMethod" value="doIt" />
</bean>
----

The above example will result in the `doIt` method being called on the `exampleBusinessObject` method (see below):

[source,java]
----
public class ExampleBusinessObject {

  // properties and collaborators

  public void doIt() {
    // do the actual work
  }
}
----

[source,xml]
----

<bean id="exampleBusinessObject" class="examples.ExampleBusinessObject"/>
----

Using the [class]`MethodInvokingJobDetailFactoryBean`, you don't need to create one-line jobs that just invoke a method, and you only need to create the actual business object and wire up the detail object.

By default, Quartz Jobs are stateless, resulting in the possibility of jobs interfering with each other.
If you specify two triggers for the same [class]`JobDetail`, it might be possible that before the first job has finished, the second one will start.
If [class]`JobDetail` classes implement the [interface]`Stateful` interface, this won't happen.
The second job will not start before the first one has finished.
To make jobs resulting from the [class]`MethodInvokingJobDetailFactoryBean` non-concurrent, set the `concurrent` flag to `false`.

[source,xml]
----

<bean id="jobDetail" class="org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean">
  <property name="targetObject" ref="exampleBusinessObject" />
  <property name="targetMethod" value="doIt" />
  <property name="concurrent" value="false" />
</bean>
----

NOTE: By default, jobs will run in a concurrent fashion.

=== Wiring up jobs using triggers and the [class]`SchedulerFactoryBean`

We've created job details and jobs.
We've also reviewed the convenience bean that allows you to invoke a method on a specific object.
Of course, we still need to schedule the jobs themselves.
This is done using triggers and a [class]`SchedulerFactoryBean`.
Several triggers are available within Quartz and Spring offers two Quartz [interface]`FactoryBean` implementations with convenient defaults: [class]`CronTriggerFactoryBean` and [class]`SimpleTriggerFactoryBean`.

Triggers need to be scheduled.
Spring offers a [class]`SchedulerFactoryBean` that exposes triggers to be set as properties.
[class]`SchedulerFactoryBean` schedules the actual jobs with those triggers.

Find below a couple of examples:

[source,xml]
----
<bean id="simpleTrigger" class="org.springframework.scheduling.quartz.SimpleTriggerFactoryBean">
    <!-- see the example of method invoking job above -->
    <property name="jobDetail" ref="jobDetail" />
    <!-- 10 seconds -->
    <property name="startDelay" value="10000" />
    <!-- repeat every 50 seconds -->
    <property name="repeatInterval" value="50000" />
</bean>

<bean id="cronTrigger" class="org.springframework.scheduling.quartz.CronTriggerFactoryBean">
    <property name="jobDetail" ref="exampleJob" />
    <!-- run every morning at 6 AM -->
    <property name="cronExpression" value="0 0 6 * * ?" />
</bean>
----

Now we've set up two triggers, one running every 50 seconds with a starting delay of 10 seconds and one every morning at 6 AM. To finalize everything, we need to set up the [class]`SchedulerFactoryBean`:

[source,xml]
----
<bean class="org.springframework.scheduling.quartz.SchedulerFactoryBean">
    <property name="triggers">
        <list>
            <ref bean="cronTrigger" />
            <ref bean="simpleTrigger" />
        </list>
    </property>
</bean>
----

More properties are available for the [class]`SchedulerFactoryBean` for you to set, such as the calendars used by the job details, properties to customize Quartz with, etc.
Have a look at the <<,SchedulerFactoryBean
      Javadoc>> for more information.
