
:numbered!:

[appendix]
= spring-form.tld

== Introduction

One of the view technologies you can use with the Spring Framework is Java Server Pages (JSPs).
To help you implement views using Java Server Pages the Spring Framework provides you with some tags for evaluating errors, setting themes and outputting internationalized messages.

Please note that the various tags generated by this form tag library are compliant with the <<,XHTML-1.0-Strict specification>> and attendant <<,DTD>>.

This appendix describes the `spring-form.tld` tag library.


== The `checkbox` tag

Renders an HTML 'input' tag with type 'checkbox'.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     accesskey
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     label
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Value to be displayed as part of the tag
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     onblur
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onchange
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onfocus
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to property for data binding
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     value
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  
|===

== The `checkboxes` tag

Renders multiple HTML 'input' tags with type 'checkbox'.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     accesskey
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     delimiter
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Delimiter to use between each 'input' tag with type 'checkbox'. There is no delimiter by default.
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     element
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Specifies the HTML element that is used to enclose each 'input' tag with type 'checkbox'.  Defaults to 'span'.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     itemLabel
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Value to be displayed as part of the 'input' tags with type 'checkbox'
                  

| 
                     items
                  
| 
                     true
                  
| 
                     true
                  
| 
                     The Collection, Map or array of objects used to generate the 'input' tags with type 'checkbox'
                  

| 
                     itemValue
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Name of the property mapped to 'value' attribute of the 'input' tags with type 'checkbox'
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     onblur
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onchange
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onfocus
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to property for data binding
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

== The `errors` tag

Renders field errors in an HTML 'span' tag.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     delimiter
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Delimiter for displaying multiple error messages. Defaults to the br tag.
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     element
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Specifies the HTML element that is used to render the enclosing errors.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Path to errors object for data binding
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

== The `form` tag

Renders an HTML 'form' tag and exposes a binding path to inner tags for binding.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     acceptCharset
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Specifies the list of character encodings for input data that is accepted by the server processing this form. The value is a space- and/or comma-delimited list of charset values. The client must interpret this list as an exclusive-or list, i.e., the server is able to accept any single character encoding per entity received.
                  

| 
                     action
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Required Attribute
                  

| 
                     commandName
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Name of the model attribute under which the form object is exposed.
                Defaults to 'command'.
                  

| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     enctype
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     method
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     modelAttribute
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Name of the model attribute under which the form object is exposed.
                Defaults to 'command'.
                  

| 
                     name
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute - added for backwards compatibility cases
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onreset
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onsubmit
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     target
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

== The `hidden` tag

Renders an HTML 'input' tag with type 'hidden' using the bound value.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to property for data binding
                  
|===

== The `input` tag

Renders an HTML 'input' tag with type 'text' using the bound value.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     accesskey
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     alt
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     autocomplete
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Common Optional Attribute
                  

| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     maxlength
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     onblur
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onchange
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onfocus
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onselect
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to property for data binding
                  

| 
                     readonly
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will make the HTML element readonly.
                  

| 
                     size
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

== The `label` tag

Renders a form field label in an HTML 'label' tag.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute.
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used only when errors are present.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     for
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to errors object for data binding
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

== The `option` tag

Renders a single HTML 'option'.
Sets 'selected' as appropriate based on bound value.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     label
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     value
                  
| 
                     true
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  
|===

== The `options` tag

Renders a list of HTML 'option' tags.
Sets 'selected' as appropriate based on bound value.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     itemLabel
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Name of the property mapped to the inner text of the 'option' tag
                  

| 
                     items
                  
| 
                     true
                  
| 
                     true
                  
| 
                     The Collection, Map or array of objects used to generate the inner 'option' tags
                  

| 
                     itemValue
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Name of the property mapped to 'value' attribute of the 'option' tag
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

== The `password` tag

Renders an HTML 'input' tag with type 'password' using the bound value.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     accesskey
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     alt
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     autocomplete
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Common Optional Attribute
                  

| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     maxlength
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     onblur
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onchange
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onfocus
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onselect
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to property for data binding
                  

| 
                     readonly
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will make the HTML element readonly.
                  

| 
                     showPassword
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Is the password value to be shown? Defaults to false.
                  

| 
                     size
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

== The `radiobutton` tag

Renders an HTML 'input' tag with type 'radio'.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     accesskey
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     label
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Value to be displayed as part of the tag
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     onblur
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onchange
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onfocus
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to property for data binding
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     value
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  
|===

== The `radiobuttons` tag

Renders multiple HTML 'input' tags with type 'radio'.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     accesskey
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     delimiter
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Delimiter to use between each 'input' tag with type 'radio'. There is no delimiter by default.
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     element
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Specifies the HTML element that is used to enclose each 'input' tag with type 'radio'.  Defaults to 'span'.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     itemLabel
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Value to be displayed as part of the 'input' tags with type 'radio'
                  

| 
                     items
                  
| 
                     true
                  
| 
                     true
                  
| 
                     The Collection, Map or array of objects used to generate the 'input' tags with type 'radio'
                  

| 
                     itemValue
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Name of the property mapped to 'value' attribute of the 'input' tags with type 'radio'
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     onblur
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onchange
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onfocus
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to property for data binding
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

== The `select` tag

Renders an HTML 'select' element.
Supports databinding to the selected option.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     accesskey
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     itemLabel
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Name of the property mapped to the inner text of the 'option' tag
                  

| 
                     items
                  
| 
                     false
                  
| 
                     true
                  
| 
                     The Collection, Map or array of objects used to generate the inner 'option' tags
                  

| 
                     itemValue
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Name of the property mapped to 'value' attribute of the 'option' tag
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     multiple
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     onblur
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onchange
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onfocus
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to property for data binding
                  

| 
                     size
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

== The `textarea` tag

Renders an HTML 'textarea'.

.Attributes
[cols="1,1,1,1", options="header"]
|===
| Attribute
| Required?
| Runtime Expression?
| Description
| 
                     accesskey
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     cols
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Required Attribute
                  

| 
                     cssClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute
                  

| 
                     cssErrorClass
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "class" - HTML Optional Attribute. Used when the bound field has errors.
                  

| 
                     cssStyle
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Equivalent to "style" - HTML Optional Attribute
                  

| 
                     dir
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     disabled
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will disable the HTML element.
                  

| 
                     htmlEscape
                  
| 
                     false
                  
| 
                     true
                  
| 
                     Enable/disable HTML escaping of rendered values.
                  

| 
                     id
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     lang
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     onblur
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onchange
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     ondblclick
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onfocus
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeydown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeypress
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onkeyup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousedown
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmousemove
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseout
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseover
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onmouseup
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     onselect
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Event Attribute
                  

| 
                     path
                  
| 
                     true
                  
| 
                     true
                  
| 
                     Path to property for data binding
                  

| 
                     readonly
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Optional Attribute. Setting the value of this attribute to 'true' (without the quotes) will make the HTML element readonly.
                  

| 
                     rows
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Required Attribute
                  

| 
                     tabindex
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  

| 
                     title
                  
| 
                     false
                  
| 
                     true
                  
| 
                     HTML Standard Attribute
                  
|===

:numbered:
