= Spring Framework Reference Documentation
The Spring Framework team and contributors https://github.com/spring-projects/spring-framework/graphs/contributors
:doc-root: https://docs.spring.io
:api-spring-framework: {doc-root}/spring-framework/docs/{spring-version}/javadoc-api/org/springframework

Welcome to the Spring Framework reference!

Please read the <<overview.adoc,Overview>> for an introduction including brief history,
design philosophy, where to ask questions, and tips to get started. For information on
what's new, or migrating from a previous version, check the
https://github.com/spring-projects/spring-framework/wiki[Github Wiki].

The reference is divided into several sections:

[horizontal]
<<core.adoc#spring-core,Core>> :: IoC container, Events, Resources, i18n, Validation,
Data Binding, Type Conversion, SpEL, AOP.
<<testing.adoc#testing,Testing>> :: Mock objects, TestContext framework,
Spring MVC Test, WebTestClient.
<<data-access.adoc#spring-data-tier,Data Access>> :: Transactions, DAO support, JDBC,
ORM, Marshalling XML.
<<web.adoc#spring-web,Web Servlet>> :: Spring MVC web framework, WebSocket,
SockJS, STOMP messaging.
<<web-reactive.adoc#spring-webflux,Web Reactive>> :: Spring WebFlux,
WebClient, WebSocket support.
<<integration.adoc#spring-integration,Integration>> :: Remoting, JMS, JCA, JMX, Email,
Tasks, Scheduling, Cache, Dynamic languages.
<<kotlin.adoc#kotlin,Kotlin>> :: Extensions, Bean Definition DSL, WebFlux DSL
<<appendix.adoc#spring-appendices,Appendix>> :: XML Schemas, JSP Tag Libraries