package org.springframework.ui.validation;

import org.springframework.ui.alert.Alert;

/**
 * A single validation failure generated by a Validator.
 * @author Keith Donald
 * @see Validator#validate(Object, java.util.List)
 */
public interface ValidationFailure {

	/**
	 * The name of the model property associated with this validation result.
	 */
	String getProperty();
	
	/**
	 * Gets the alert for this validation failure, appropriate for rendering the failure to the user.
	 */
	Alert getAlert();
}
