[[mvc-config-api-version]]
= API Version

[.small]#xref:web/webflux/config.adoc#webflux-config-api-version[See equivalent in the Reactive stack]#

To enable API versioning with a request header, use the following:

include-code::./WebConfiguration[tag=snippet,indent=0]

Alternatively, the version can be resolved from a request parameter, from a path segment,
or  through a custom `ApiVersionResolver`.

TIP: When using a path segment, consider configuring a shared path prefix externally
in xref:web/webmvc/mvc-config/path-matching.adoc[Path Matching] options.

Raw version values are parsed with `SemanticVersionParser` by default, but you can use
a custom xref:web/webmvc-versioning.adoc#mvc-versioning-parser[ApiVersionParser].

"Supported" versions are transparently detected from versions declared in request mappings
for convenience, but you can turn that off through a flag in the MVC config, and use only
the versions configured explicitly in the config. Requests with a version that is not
supported are rejected with `InvalidApiVersionException` resulting in a 400 response.

Once API versioning is configured, you can begin to map requests to
xref:web/webmvc/mvc-controller/ann-requestmapping.adoc#mvc-ann-requestmapping-version[controller methods]
according to the request version.