[[mvc-servlet-special-bean-types]]
= Special Bean Types

[.small]#<<web-reactive.adoc#webflux-special-bean-types, See equivalent in the Reactive stack>>#

The `DispatcherServlet` delegates to special beans to process requests and render the
appropriate responses. By "`special beans`" we mean Spring-managed `Object` instances that
implement framework contracts. Those usually come with built-in contracts, but
you can customize their properties and extend or replace them.

The following table lists the special beans detected by the `DispatcherServlet`:

[[mvc-webappctx-special-beans-tbl]]
[cols="1,2", options="header"]
|===
| Bean type| Explanation

| `HandlerMapping`
| Map a request to a handler along with a list of
  <<mvc-handlermapping-interceptor, interceptors>> for pre- and post-processing.
  The mapping is based on some criteria, the details of which vary by `HandlerMapping`
  implementation.

  The two main `HandlerMapping` implementations are `RequestMappingHandlerMapping`
  (which supports `@RequestMapping` annotated methods) and `SimpleUrlHandlerMapping`
  (which maintains explicit registrations of URI path patterns to handlers).

| `HandlerAdapter`
| Help the `DispatcherServlet` to invoke a handler mapped to a request, regardless of
  how the handler is actually invoked. For example, invoking an annotated controller
  requires resolving annotations. The main purpose of a `HandlerAdapter` is
  to shield the `DispatcherServlet` from such details.

| <<mvc-exceptionhandlers, `HandlerExceptionResolver`>>
| Strategy to resolve exceptions, possibly mapping them to handlers, to HTML error
  views, or other targets. See <<mvc-exceptionhandlers>>.

| <<mvc-viewresolver, `ViewResolver`>>
| Resolve logical `String`-based view names returned from a handler to an actual `View`
  with which to render to the response. See <<mvc-viewresolver>> and <<mvc-view>>.

| <<mvc-localeresolver, `LocaleResolver`>>, <<mvc-timezone, LocaleContextResolver>>
| Resolve the `Locale` a client is using and possibly their time zone, in order to be able
  to offer internationalized views. See <<mvc-localeresolver>>.

| <<mvc-themeresolver, `ThemeResolver`>>
| Resolve themes your web application can use -- for example, to offer personalized layouts.
  See <<mvc-themeresolver>>.

| <<mvc-multipart, `MultipartResolver`>>
| Abstraction for parsing a multi-part request (for example, browser form file upload) with
  the help of some multipart parsing library. See <<mvc-multipart>>.

| <<mvc-flash-attributes, `FlashMapManager`>>
| Store and retrieve the "`input`" and the "`output`" `FlashMap` that can be used to pass
  attributes from one request to another, usually across a redirect.
  See <<mvc-flash-attributes>>.
|===



