[[spring-core]]
= Core Technologies 

[partintro]
--
This part of the reference documentation covers all of those technologies that are
absolutely integral to the Spring Framework.

Foremost amongst these is the Spring Framework's Inversion of Control (IoC) container. A
thorough treatment of the Spring Framework's IoC container is closely followed by
comprehensive coverage of Spring's Aspect-Oriented Programming (AOP) technologies. The
Spring Framework has its own AOP framework, which is conceptually easy to understand,
and which successfully addresses the 80% sweet spot of AOP requirements in Java
enterprise programming.

Coverage of Spring's integration with AspectJ (currently the richest - in terms of
features - and certainly most mature AOP implementation in the Java enterprise space) is
also provided.


* <<beans>>
* <<resources>>
* <<validation>>
* <<expressions>>
* <<aop>>
* <<aop-api>>
--



include::core-beans.adoc[leveloffset=+1]

include::core-resources.adoc[leveloffset=+1]

include::core-validation.adoc[leveloffset=+1]

include::core-expressions.adoc[leveloffset=+1]

include::core-aop.adoc[leveloffset=+1]

include::core-aop-api.adoc[leveloffset=+1]

